### PR TITLE
Regional example

### PR DESCRIPTION
**Pull request by liamtoney**
This PR updates the regional example, replacing the old bolide location with a January 2022 Hunga eruption location.

The new example is faster and more interesting.

Note: This PR is dependent on a _waveform_collection_ PR that must be merged first: https://github.com/uafgeotools/waveform_collection/pull/25 (after that PR is merged, the temporary changes to `environment.yml` can be reversed)

### CODE REVIEW

**Comment by liamtoney** [comment]
Play with the new regional example on Binder here: [](https://mybinder.org/v2/gh/uafgeotools/rtm/regional-example)

**Comment by liamtoney** [comment]
@davidfee5 this PR is now ready for review.

**Comment by davidfee5** [comment]
The imports won't load for me when I try to run the jupyter notebook. See attached image. Note this it outside the Binder usage so perhaps outdated or something?
Screen Shot 2022-04-06 at 4 38 33 PM

**Comment by liamtoney** [comment]
Have you re-built the `rtm` env recently? Try re-building with
```python
conda env create
```
in the directory root, per the [installation instructions](https://github.com/uafgeotools/rtm#installation). You might have an outdated env.

**Comment by liamtoney** [comment]
In your screenshot, the first code cell (which imports everything) is not visible at all. Accidental delete? Here's the link to the file itself: https://github.com/uafgeotools/rtm/blob/regional-example/example_regional.ipynb

**Comment by davidfee5** [comment]
Weird...those imports did get deleted somehow. Explains why they weren't there:) Working now.

**Review by davidfee5 — APPROVED** [review]
Looks good to me. I tweaked the parameters a bit but think the ones here are pretty good already. Nice example!

**Pull request merged**
